dataset:
  spot_size: 1.8
  image_size: 128
  augmentation:
    size: 5
    amplitude: 1.2
  dot_angle_range_degrees: 360
trainer:
  batch_size: 8
  dataloader_num_workers: 0
  n_steps: 3000
  num_workers: 4
  learning_rate: 0.0003
post_train_evaluator:
  n_samples: 256
accuracy_measurer:
  spot_measure_radius: 2.0
by_forward_pass:
  image_size: 768